### ISSUE TITLE
동대륙 - 서대륙 복귀 퀘스트 오류

### ISSUE THREAD

**Issue by koaTS** [dkpark89/tome4-korean-translation#297]
다이아몬드, 단검, 돈 다 있어도 퀘스트가 완료되지 않고 포탈이 생기지 않는 오류가 있습니다.

data/quest 쪽 문제는 아닌 거 같은데 혹시 아시는분 수정 부탁드립니다.

**Comment by KimRuin** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

alkahest7@naver.com 님께 보내신 메일 <[tome4-korean-translation] 동대륙 - 서대륙 복귀 퀘스트 오류 (#297)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by dkpark89** [comment]
혹. 해당 상태의 (또는 바로 직전의) 세이브 파일이 있으면 디버깅에 도움이 되지않을까 싶습니다.

**Comment by dkpark89** [comment]
제메키스가 말했습니다. '관문이 완성되었네! 라는 퀘스트 완료 대화는 뜨는지요?

**Comment by KimRuin** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

alkahest7@naver.com 님께 보내신 메일 <Re: [tome4-korean-translation] 동대륙 - 서대륙 복귀 퀘스트 오류 (#297)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
